# Generated by Django 3.2.18 on 2025-02-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysecondapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='age',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='account',
            name='rule',
            field=models.CharField(default='user', max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='suspended',
            field=models.BooleanField(default=False),
        ),
    ]
